spring:
  application:
    name: character-group-bot
  
  datasource:
    url: jdbc:h2:file:./data/botdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    enabled: true

telegram:
  bot:
    name: {}
    token: {}
    admin-secret: {}
logging:
  level:
    com.gaming.bot: DEBUG
    org.springframework: INFO
    org.hibernate: INFO
